import { FAMILY, TOOLS_LIMIT } from './consts';
import type { ModelDefinition, ReasoningEffort, ThinkingCapability } from './types';

/**
 * Standard capability set for OpenAI-compatible reasoning models served by
 * Command Code: tool calling enabled, no native vision unless the underlying
 * model supports it (annotated per-entry below), and a 4-level thinking
 * effort selector.
 */
const THINKING: ThinkingCapability = {
	supportedEfforts: ['low', 'medium', 'high'] as const,
	defaultEffort: 'medium' as ReasoningEffort,
	canDisable: true,
};

const NO_THINKING = false;

/**
 * Compile-time model registry for the models available on Command Code Go.
 *
 * This is intentionally an allowlist rather than a copy of every upstream
 * model. Keep entries here aligned with the Go plan catalog so unsupported
 * models never appear in Copilot Chat's picker.
 *
 * Each entry uses the upstream `vendor/name` slug from `cmdc --list-models`
 * as the model id, which is sent unchanged to the Generate API.
 *
 * Vision-capable models are flagged with `imageInput: true`. Tool calling
 * is assumed to be supported for every model — adjust per-entry if a
 * specific upstream omits it.
 */

export const MODELS: readonly ModelDefinition[] = [
	// ---- Alibaba ----
	{
		id: 'qwen/qwen3.6-max-preview',
		name: 'Qwen 3.6 Max Preview',
		family: FAMILY,
		version: '3.6',
		detail: 'vibe coding & efficient agent execution',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.6-plus',
		name: 'Qwen 3.6 Plus',
		family: FAMILY,
		version: '3.6',
		detail: 'agentic coding & reasoning',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.7-flash',
		name: 'Qwen 3.7 Flash',
		family: FAMILY,
		version: '3.7',
		detail: 'fast low-cost agentic coding & reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.7-max',
		name: 'Qwen 3.7 Max',
		family: FAMILY,
		version: '3.7',
		detail: 'frontier coding & long-horizon agent execution',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.7-plus',
		name: 'Qwen 3.7 Plus',
		family: FAMILY,
		version: '3.7',
		detail: 'agentic coding & reasoning at lower cost',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.8-max',
		name: 'Qwen 3.8 Max',
		family: FAMILY,
		version: '3.8',
		detail: 'autonomous long-horizon coding & professional work',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.8-max-0902',
		name: 'Qwen 3.8 Max 0902',
		family: FAMILY,
		version: '3.8',
		detail: 'upgraded Qwen 3.8 Max: stronger coding & agentic tool use',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.8-27b',
		name: 'Qwen 3.8 27B',
		family: FAMILY,
		version: '3.8',
		detail: 'compact vision-language coding & agentic work',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.8-flash',
		name: 'Qwen 3.8 Flash',
		family: FAMILY,
		version: '3.8',
		detail: 'fast low-cost agentic coding & reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},
	{
		id: 'qwen/qwen3.8-omni-flash',
		name: 'Qwen 3.8 Omni Flash',
		family: FAMILY,
		version: '3.8',
		detail: 'omni-modal understanding & multimedia agentic work',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Alibaba',
	},

	// ---- DeepSeek ----
	{
		id: 'deepseek/deepseek-v4-flash',
		name: 'DeepSeek V4 Flash',
		family: FAMILY,
		version: 'v4',
		detail: 'fast hybrid-attention reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-flash-fast',
		name: 'DeepSeek V4 Flash Fast',
		family: FAMILY,
		version: 'v4',
		detail: 'low-latency V4 Flash deployment',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-flash-vision-exp',
		name: 'DeepSeek V4 Flash Vision (exp)',
		family: FAMILY,
		version: 'v4',
		detail: 'fast hybrid-attention reasoning with vision',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4-pro',
		name: 'DeepSeek V4 Pro',
		family: FAMILY,
		version: 'v4',
		detail: 'hybrid-attention long-context reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4.1-flash',
		name: 'DeepSeek V4.1 Flash',
		family: FAMILY,
		version: 'v4.1',
		detail: 'V4.1 hybrid-attention reasoning with vision',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'DeepSeek',
	},
	{
		id: 'deepseek/deepseek-v4.1-flash-fast',
		name: 'DeepSeek V4.1 Flash Fast',
		family: FAMILY,
		version: 'v4.1',
		detail: 'high throughput V4.1 Flash deployment',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'DeepSeek',
	},

	// ---- InclusionAI ----
	{
		id: 'inclusionai/ling-3.0-flash-sante:free',
		name: 'Ling 3.0 Flash Sante',
		family: FAMILY,
		version: '3.0',
		detail: 'health & medicine tuned lightweight-MoE, still strong on code',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'InclusionAI',
	},
	{
		id: 'inclusionai/ling-3.1-flash:free',
		name: 'Ling 3.1 Flash',
		family: FAMILY,
		version: '3.1',
		detail: 'hybrid-reasoning MoE for coding & tool-using agents',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'InclusionAI',
	},

	// ---- Meituan ----
	{
		id: 'meituan/longcat-2.0',
		name: 'LongCat 2.0',
		family: FAMILY,
		version: '2.0',
		detail: 'trillion-parameter agentic coding with 1M context',
		maxInputTokens: 1016576,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Meituan',
	},

	// ---- Meta ----
	{
		id: 'meta/muse-spark-1.2-contributor',
		name: 'Muse Spark 1.2 Contributor',
		family: FAMILY,
		version: '1.2',
		detail: 'Muse Spark 1.2 at ~95% off',
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},
	{
		id: 'meta/muse-spark-1.3-contributor',
		name: 'Muse Spark 1.3 Contributor',
		family: FAMILY,
		version: '1.3',
		detail: 'Muse Spark 1.3 at up to 95% off',
		maxInputTokens: 917504,
		maxOutputTokens: 131072,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Meta',
	},

	// ---- MiniMax ----
	{
		id: 'minimaxai/minimax-m2.5',
		name: 'MiniMax M2.5',
		family: FAMILY,
		version: 'm2.5',
		detail: 'cross-platform full-stack agentic dev',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'MiniMax',
	},
	{
		id: 'minimaxai/minimax-m2.7',
		name: 'MiniMax M2.7',
		family: FAMILY,
		version: 'm2.7',
		detail: 'end-to-end software engineering agent',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'MiniMax',
	},
	{
		id: 'minimaxai/minimax-m3',
		name: 'MiniMax M3',
		family: FAMILY,
		version: 'm3',
		detail: 'frontier coding, agents & native multimodality',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'MiniMax',
	},

	// ---- Moonshot AI ----
	{
		id: 'moonshotai/kimi-k2.5',
		name: 'Kimi K2.5',
		family: FAMILY,
		version: 'k2.5',
		detail: 'multimodal frontend coding',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/kimi-k2.6',
		name: 'Kimi K2.6',
		family: FAMILY,
		version: 'k2.6',
		detail: 'long-horizon coding with vision',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/kimi-k2.7-code',
		name: 'Kimi K2.7 Code',
		family: FAMILY,
		version: 'k2.7',
		detail: 'improved long-horizon coding with vision',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/kimi-k2.7-code-highspeed',
		name: 'Kimi K2.7 Code HighSpeed',
		family: FAMILY,
		version: 'k2.7',
		detail: 'high-speed long-horizon coding with vision',
		maxInputTokens: 230000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},
	{
		id: 'moonshotai/kimi-k3',
		name: 'Kimi K3',
		family: FAMILY,
		version: 'k3',
		detail: 'long-horizon coding & knowledge work with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Moonshot AI',
	},

	// ---- NVIDIA ----
	{
		id: 'nvidia/nemotron-3-ultra-550b-a55b',
		name: 'Nemotron 3 Ultra',
		family: FAMILY,
		version: '3',
		detail: 'open reasoning model for long-horizon autonomous agents',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'NVIDIA',
	},

	// ---- OpenAI ----
	{
		id: 'gpt-5.6-luna',
		name: 'GPT-5.6 Luna',
		family: FAMILY,
		version: '5.6',
		detail: 'optimized for cost-sensitive workloads',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},
	{
		id: 'gpt-6-luna',
		name: 'GPT-6 Luna',
		family: FAMILY,
		version: '6',
		detail: 'most efficient OpenAI model for focused, high-volume tasks',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'OpenAI',
	},

	// ---- Poolside ----
	{
		id: 'poolside/laguna-s-2.1-free',
		name: 'Laguna S 2.1',
		family: FAMILY,
		version: '2.1',
		detail: 'open-weight agentic coding and long-horizon work',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Poolside',
	},

	// ---- Stealth ----
	{
		id: 'stealth/pixel-canary',
		name: 'Pixel Canary',
		family: FAMILY,
		version: 'canary',
		detail: 'FREE stealth coding model for web and mobile apps',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Stealth',
	},
	{
		id: 'stealth/space-bunny-alpha',
		name: 'Space Bunny Alpha',
		family: FAMILY,
		version: 'alpha',
		detail: 'FREE stealth model with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Stealth',
	},

	// ---- StepFun ----
	{
		id: 'stepfun/step-3.5-flash',
		name: 'Step 3.5 Flash',
		family: FAMILY,
		version: '3.5',
		detail: 'fast sparse-MoE agentic reasoning',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'StepFun',
	},
	{
		id: 'stepfun/step-3.7-flash',
		name: 'Step 3.7 Flash',
		family: FAMILY,
		version: '3.7',
		detail: 'multimodal sparse-MoE reasoning',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'StepFun',
	},
	{
		id: 'stepfun/step-5-preview',
		name: 'Step 5 Preview',
		family: FAMILY,
		version: '5',
		detail: '600B sparse-MoE agentic coding with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'StepFun',
	},

	// ---- Tencent ----
	{
		id: 'tencent/hy3-paid',
		name: 'Tencent Hy3',
		family: FAMILY,
		version: 'hy3',
		detail: 'sparse-MoE reasoning & agentic tool use',
		maxInputTokens: 230144,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Tencent',
	},
	{
		id: 'tencent/hy4-preview',
		name: 'Tencent Hy4 Preview',
		family: FAMILY,
		version: 'hy4',
		detail: 'agentic coding & sustained multi-step tool use',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Tencent',
	},

	// ---- Thinking Machines ----
	{
		id: 'thinkingmachines/inkling',
		name: 'Inkling',
		family: FAMILY,
		version: 'inkling',
		detail: 'multimodal MoE reasoning',
		maxInputTokens: 224000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Thinking Machines',
	},
	{
		id: 'thinkingmachines/inkling-small',
		name: 'Inkling Small',
		family: FAMILY,
		version: 'inkling',
		detail: 'lightweight MoE reasoning at lower cost and latency',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Thinking Machines',
	},

	// ---- xAI ----
	{
		id: 'xai/grok-4.5',
		name: 'Grok 4.5',
		family: FAMILY,
		version: '4.5',
		detail: 'smartest model for coding, agentic tasks, knowledge work',
		maxInputTokens: 468000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'xAI',
	},

	// ---- Xiaomi ----
	{
		id: 'xiaomi/mimo-v2.5',
		name: 'MiMo V2.5',
		family: FAMILY,
		version: 'v2.5',
		detail: 'efficient long-context agentic coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: NO_THINKING },
		category: 'Xiaomi',
	},
	{
		id: 'xiaomi/mimo-v2.5-pro',
		name: 'MiMo V2.5 Pro',
		family: FAMILY,
		version: 'v2.5',
		detail: 'high-capability long-context agentic coding',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Xiaomi',
	},
	{
		id: 'xiaomi/mimo-v2.6-flash',
		name: 'MiMo V2.6 Flash',
		family: FAMILY,
		version: 'v2.6',
		detail: 'efficient multimodal agentic coding with 1M context',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Xiaomi',
	},
	{
		id: 'xiaomi/mimo-v2.6-pro',
		name: 'MiMo V2.6 Pro',
		family: FAMILY,
		version: 'v2.6',
		detail: 'flagship multimodal agentic coding with 1M context',
		maxInputTokens: 1018000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Xiaomi',
	},

	// ---- Z AI ----
	{
		id: 'zai-org/glm-5',
		name: 'GLM-5',
		family: FAMILY,
		version: '5',
		detail: 'multi-mode thinking & long-range planning',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/glm-5.1',
		name: 'GLM-5.1',
		family: FAMILY,
		version: '5.1',
		detail: 'long-horizon autonomous coding agent',
		maxInputTokens: 168000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/glm-5.2',
		name: 'GLM-5.2',
		family: FAMILY,
		version: '5.2',
		detail: 'powerful coding with 1M context and long-horizon tasks',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/glm-5.2-fast',
		name: 'GLM-5.2 Fast',
		family: FAMILY,
		version: '5.2',
		detail: 'high-throughput GLM-5.2 with 1M context',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: NO_THINKING },
		category: 'Z AI',
	},
	{
		id: 'zai-org/glm-5.3',
		name: 'GLM-5.3',
		family: FAMILY,
		version: '5.3',
		detail: 'frontier coding with emergent cyber capabilities',
		maxInputTokens: 968000,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: false, thinking: THINKING },
		category: 'Z AI',
	},
	{
		id: 'z-ai/glm-5.3-flash',
		name: 'GLM-5.3 Flash',
		family: FAMILY,
		version: '5.3',
		detail: 'fast, affordable GLM coding with 1M context',
		maxInputTokens: 1016576,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Z AI',
	},
	{
		id: 'z-ai/glm-5.3-flashx',
		name: 'GLM-5.3 FlashX',
		family: FAMILY,
		version: '5.3',
		detail: 'high-speed GLM-5.3 Flash with 1M context',
		maxInputTokens: 1016576,
		maxOutputTokens: 32000,
		capabilities: { toolCalling: TOOLS_LIMIT, imageInput: true, thinking: THINKING },
		category: 'Z AI',
	},
];
